# Використовуємо офіційний образ nginx
FROM nginx:latest

# Копіюємо файли вашого веб-сайту у контейнер
COPY . /usr/share/nginx/html

# Налаштовуємо потрібні параметри, порт
EXPOSE 80

# Запускаємо веб-сервер
CMD ["nginx", "-g", "daemon off;"]

